add oxocarbon theme
alacritty/alacritty-theme pull request #110
Opened 2024-07-30 19:11 UTC by 992f9e

This is a commit to add the Oxocarbon vim theme that is my go to option when i'm using vim, and also removed the synthwave picture that was on the root of project bloating it, as it already exists under the images folder!

2024-07-30 23:21 UTC, chrisduerr requested changes

2024-07-30 23:21 UTC, chrisduerr commented on synthwave_84.png
I didn't actually notice this file was accidentally pushed to the root of the project. Can you move it to the correct location? I believe the PR introducing it meant to overwrite the existing file since it changed some colors.

2024-07-31 00:00 UTC, 992f9e commented on synthwave_84.png
Sure thing, i moved the new pic to the images folder in this new commit

2024-07-31 01:38 UTC, chrisduerr approved these changes

2024-07-31 01:38 UTC, merged