Add Kimbie themes
alacritty/alacritty-theme pull request #136
Opened 2024-12-30 09:52 UTC by AaronPed

Add Kimbie dark and Kimbie light themes

2024-12-31 16:58 UTC, chrisduerr requested changes

2024-12-31 16:58 UTC, chrisduerr commented on images/kimbie_light.png
This image seems to be about half the size of the dark image and shows up significantly smaller in the theme overview. Did you manually shrink this? I think it would be best to recapture to have a more consistent overview.

2025-01-03 10:13 UTC, chrisduerr approved these changes

2025-01-03 10:14 UTC, merged

2025-01-03 10:14 UTC, AaronPed commented on images/kimbie_light.png
Seems to have happened when I exported the screenshot compared to just snipping it directly.
New image is the correct size.