Add Gruvbox Material Medium Dark/Light Themes
alacritty/alacritty-theme pull request #29
Opened 2023-06-01 17:25 UTC by Samylov-Mikhail

Hello! I would like to add Gruvbox Material Medium Dark/Light themes. 

Sources:

* https://github.com/sainnhe/gruvbox-material/blob/3fff63b0d6a425ad1076a260cd4f6da61d1632b1/autoload/gruvbox_material.vim
* https://gist.github.com/sainnhe/ad5cbc4f05c4ced83f80e54d9a75d22f

2023-06-01 23:04 UTC, chrisduerr requested changes

2023-06-01 23:04 UTC, chrisduerr commented on themes/gruvbox_material.yaml
You say this is kept for compatibility, but this is a completely different theme?

Did the upstream theme change?

2023-06-02 08:31 UTC, Samylov-Mikhail commented on themes/gruvbox_material.yaml
The upstream theme colors required for alacrity didn't change. But [the current theme](https://github.com/alacritty/alacritty-theme/blob/261b35710df2ef6fe540109bffb9590270774af7/themes/gruvbox_material.yaml) doesn't match [the original one](https://github.com/sainnhe/gruvbox-material/blob/3fff63b0d6a425ad1076a260cd4f6da61d1632b1/autoload/gruvbox_material.vim). For example, [the foreground color](https://github.com/alacritty/alacritty-theme/blob/261b35710df2ef6fe540109bffb9590270774af7/themes/gruvbox_material.yaml#L5) doesn't exist in the original theme. So I have updated the Gruvbox Material Medium Dark theme.

2023-06-05 22:43 UTC, chrisduerr requested changes

2023-06-05 22:43 UTC, chrisduerr commented on themes/gruvbox_material.yaml
Then I recommend just ditching the old one. We don't need to maintain compatibility here if people want access to old versions they can just checkout specific commits.

2023-06-08 05:19 UTC, chrisduerr approved these changes

2023-06-08 05:19 UTC, merged