adds ashes themes
alacritty/alacritty-theme pull request #64
Opened 2024-01-09 18:52 UTC by lestex

What: adds ashes dark/light themes

2024-01-09 23:42 UTC, chrisduerr requested changes

2024-01-09 23:42 UTC, chrisduerr commented on themes/ashes_dark.toml
> +white   =  '#f3f4f5'
```suggestion
white   = '#f3f4f5'
```

2024-01-09 23:42 UTC, chrisduerr commented on themes/ashes_light.toml
> +white   =  '#f3f4f5'
```suggestion
white   = '#f3f4f5'
```

2024-01-10 04:04 UTC, lestex commented
my bad, fixed

2024-01-10 20:51 UTC, chrisduerr approved these changes

2024-01-10 20:52 UTC, merged