fix(toml): alter bright black color
alacritty/alacritty-theme pull request #68
Opened 2024-01-19 19:54 UTC by rafaeloledo

without the changes, the color is barely visible
![image](https://github.com/alacritty/alacritty-theme/assets/51183852/38df4131-2651-43c3-932a-2d3bb8976f81)

with the changes
![image](https://github.com/alacritty/alacritty-theme/assets/51183852/b0e67717-40cd-4a1b-9962-e935618346e2)

print_colors template
![image](https://github.com/alacritty/alacritty-theme/assets/51183852/36a72b31-85d3-41fd-b41d-eb867844aa67)

2024-01-19 22:45 UTC, chrisduerr requested changes
What are these changes based on other than your opinion?

2024-01-20 14:14 UTC, rafaeloledo commented
> What are these changes based on other than your opinion?

I mean, is based on my opinion for sure. But visible colors isn't a expected functionality?

When i used the theme, i thought it was a problem with my fish autosuggestions.

2024-01-20 18:59 UTC, chrisduerr commented
> But visible colors isn't a expected functionality?

It's not. This repo is maintaining about a billion popular themes with the goal of being accurate to the original theme. If we start randomly modifying themes then we might as well not reference the original themes at all.

2024-01-20 18:59 UTC, closed without merging

2024-01-20 19:39 UTC, rafaeloledo commented
I get the point. At least if someone want to use the solarized dark theme and get the same problem, it's documented here.

2024-12-17 16:48 UTC, isra17 commented
>It's not. This repo is maintaining about a billion popular themes with the goal of being accurate to the original theme. If we start randomly modifying themes then we might as well not reference the original themes at all.

I came here for the same issue. Any app using "Dark Gray"/"Bright Black" are simply unusable.

I'm curious as to where you picked your "original themes" values since Solarized do not define things such as "Dark Gray".

If anything, the value set here as Dark Gray is actually Base03 which is well defined as a Background Tone. It feels like a more proper value would be the darker Content Tone as suggested in this PR (Base01).

Ref: 
![image](https://github.com/user-attachments/assets/43917149-e8e3-4190-b755-1fbe621b7831)