add gruvbox material hard themes (light and dark)
alacritty/alacritty-theme pull request #78
Opened 2024-02-21 08:51 UTC by matthiasschaub

2024-02-21 21:09 UTC, chrisduerr requested changes

2024-02-21 21:09 UTC, chrisduerr commented on images/gruvbox_material_hard_ligh.png
light is spelled incorrectly here.

2024-02-22 19:51 UTC, matthiasschaub commented on images/gruvbox_material_hard_ligh.png
Thanks for the review. I fixed it.

2024-02-22 20:18 UTC, chrisduerr approved these changes
LGTM

2024-02-22 20:18 UTC, merged