Adding Enfocado theme
alacritty/alacritty-theme pull request #92
Opened 2024-04-12 05:38 UTC by codex0x09

adding Enfocado theme (it contents four flavors),

2024-04-12 09:07 UTC, kchibisov commented
What is the source of this theme? Just you created yourself?

2024-04-12 17:57 UTC, codex0x09 commented
- alacritty-enfocado theme's inspired form vim-enfocado (https://github.com/wuelnerdotexe).
- alacritty-enfocado (https://github.com/codex0x09/alacritty-enfocado) was wrote by codex0x09.
- there are some details should be in alacritty-enfocado repository.

2024-04-12 18:24 UTC, chrisduerr commented
Could you link to the **original** source of the colors in the theme?

Also please don't link to your own repository, since that should be useless once this PR is merged, thus making it an unnecessary point of failure.

2024-04-12 18:46 UTC, codex0x09 commented
it was inspired from vim-enfocado https://github.com/wuelnerdotexe/vim-enfocado

2024-04-12 20:43 UTC, chrisduerr commented
> it was inspired from vim-enfocado https://github.com/wuelnerdotexe/vim-enfocado

Then document that as the source.

2024-04-12 21:15 UTC, codex0x09 commented
I apologize for being late, my connection is not good.
I'v changed the source in the each theme file to vim-enfocado repo,
but if any one see the source and than go there, they wont find the source code of the alacritty-enfocado theme.
could you teach me why this ?

2024-04-15 18:05 UTC, chrisduerr commented
> they wont find the source code of the alacritty-enfocado theme

They're looking at the markup of the theme when reading it in this repo. It's the sole truth as far as Alacritty themes go.
The only thing they might be curious about is what these colors are supposed to be based on.

2024-04-15 18:09 UTC, chrisduerr requested changes

2024-04-15 18:09 UTC, chrisduerr commented on themes/enfocado_neon_dark.toml
> +cyan    = '#56b8c9'
How did you arrive at these colors? They do not match the enfocado theme source.

2024-04-15 21:49 UTC, codex0x09 commented
> > they wont find the source code of the alacritty-enfocado theme
> 
> They're looking at the markup of the theme when reading it in this repo. It's the sole truth as far as Alacritty themes go. The only thing they might be curious about is what these colors are supposed to be based on.

I can't thank you enough for all your patience and giving to me valuable information.
Thank you so much.

2024-04-15 21:58 UTC, codex0x09 commented on themes/enfocado_neon_dark.toml
> +cyan    = '#56b8c9'
I've modified those color, I thought in this way they become good!
if not or  they should not be modified, than I'm going to back them as they was.

2024-04-15 22:09 UTC, codex0x09 commented on themes/enfocado_neon_dark.toml
> +cyan    = '#56b8c9'
I've no idea, what should I do ?

2024-04-16 19:06 UTC, chrisduerr commented on themes/enfocado_neon_dark.toml
> +cyan    = '#56b8c9'
The goal of these shared themes is to give people easy access to popular themes. If you modify themes to be your personal ideal colorscheme instead then the potential userbase for that is exactly 1 person, at which point there's no reason for us to host that theme.

So generally speaking the original colors should be used, so when someone interested in the enfocado theme looks through this repository, it's actually what they get.

2024-04-16 19:53 UTC, codex0x09 commented on themes/enfocado_neon_dark.toml
> +cyan    = '#56b8c9'
I'm going to back theme(enfocado_neon*), but enfocado's author replace the blue colors with the violet colors !!
I note that: he set the blue one of the main colors in the (enfocado_nature*),
while the violet takes the place of blue in (enfocado_neon*).
based on this I'm going re-set the color to match the original theme.

2024-04-16 22:59 UTC, codex0x09 commented
I'm sorry, there are many commits. I'm trying to keep it simple but...
I hope now it's become as it should be !

2024-04-17 00:57 UTC, chrisduerr requested changes
I've only gone through and checked the colors of the dark theme, of which several were not matching upstream.

I'm not sure what the problem is here, it shouldn't be that difficult to copy some hex colors.

2024-04-17 00:57 UTC, chrisduerr commented on README.md
> +|                                                **_enfocado_neon_light_**<br>[source](https://github.com/wuelnerdotexe/vim-enfocado.git)           |![enfocado_neon_light](images/enfocado_neon_light.
Where did you get the names of these colorschemes from? From the theme's readme it seems like both nature and neon have the same colors, but they just use them for different syntax tokens (which is irrelevant for Alacritty).

2024-04-17 00:57 UTC, chrisduerr commented on themes/enfocado_nature_dark.toml
> +yellow  = '#dbb32b'
```suggestion
yellow  = '#dbb32d'
```

Typo?

2024-04-17 00:57 UTC, chrisduerr commented on themes/enfocado_nature_dark.toml
> +magenta = '#eb4eb7'
Shouldn't this be `#eb6eb7`?

2024-04-17 00:57 UTC, chrisduerr commented on themes/enfocado_nature_dark.toml
> +cyan    = '#56b8c9'
Shouldn't this be `#3fc5b7`?

2024-04-17 00:57 UTC, chrisduerr commented on themes/enfocado_nature_dark.toml
> +blue    = '#4f9cf3'
```suggestion
blue    = '#4f9cfe'
```

2024-04-17 00:57 UTC, chrisduerr commented on themes/enfocado_nature_dark.toml
> +magenta = '#fb4fb7'
```suggestion
magenta = '#ff81ca'
```

2024-04-17 00:57 UTC, chrisduerr commented on themes/enfocado_nature_dark.toml
> +cyan    = '#3fc5b7'
```suggestion
cyan    = '#56d8c9'
```

2024-04-17 19:49 UTC, codex0x09 commented
> I've only gone through and checked the colors of the dark theme, of which several were not matching upstream.
> 
> I'm not sure what the problem is here, it shouldn't be that difficult to copy some hex colors.

I've made many changes in the original colors when I did PR,
when you've checked the dark theme, I've removed all my change even on that you not talk about yet, which are the other dark and the light themes.
I fill that I've broken things or made many mistakes, 
if it possible, remove my PR and I'm going to do all your recommendations and then
I'll do PR  again !,

2024-04-17 20:07 UTC, codex0x09 commented on README.md
> +|                                                **_enfocado_neon_light_**<br>[source](https://github.com/wuelnerdotexe/vim-enfocado.git)           |![enfocado_neon_light](images/enfocado_neon_light.
The name 'alacritty-enfocado' is inspired form 'vim-enfocado' which is this theme for Alacritty terminal not made by alacritty, this was my thought !.

I thought that (nature-dark and neon-dark) are different as well as the lights,
based on the images in the enfocado's readme, this everything.

No problem, it's possible to change names or even removing neon-[dark | light], as long as you see that right and should be.

2024-04-17 20:16 UTC, codex0x09 commented on themes/enfocado_nature_dark.toml
> +yellow  = '#dbb32b'
I apologize for that, I've removed everything(enfocado theme) from master branch and then rewrite the colors again in another branch, it was mistake.

2024-04-17 20:29 UTC, codex0x09 commented on themes/enfocado_nature_dark.toml
> +magenta = '#eb4eb7'
yes you're right, I've made mistake here

2024-04-17 22:38 UTC, chrisduerr commented on README.md
> +|                                                **_enfocado_neon_light_**<br>[source](https://github.com/wuelnerdotexe/vim-enfocado.git)           |![enfocado_neon_light](images/enfocado_neon_light.
Considering that as far as I can tell the enfocado theme just has different colors for different syntax tokens with the two different themes, I think it makes sense to only have on enfocado dark/light theme, not two of each.

2024-04-18 23:29 UTC, codex0x09 commented on README.md
> +|                                                **_enfocado_neon_light_**<br>[source](https://github.com/wuelnerdotexe/vim-enfocado.git)           |![enfocado_neon_light](images/enfocado_neon_light.
Okay no problem,
which tow should I remove (one of dark and light themes )?!!
what is about the name alacritty-enfocado ?
the theme name will become enfocado-dark and enfocado-light !! as you've mentioned

2024-04-22 06:45 UTC, codex0x09 commented on README.md
> +|                                                **_enfocado_neon_light_**<br>[source](https://github.com/wuelnerdotexe/vim-enfocado.git)           |![enfocado_neon_light](images/enfocado_neon_light.
I agree with you.

2024-04-22 06:56 UTC, codex0x09 commented on README.md
> +|                                                **_enfocado_neon_light_**<br>[source](https://github.com/wuelnerdotexe/vim-enfocado.git)           |![enfocado_neon_light](images/enfocado_neon_light.
I apologize for being late.

2024-04-22 07:16 UTC, codex0x09 commented
Now, Enfocado theme has only tow mode dark / light.

2024-04-22 19:17 UTC, chrisduerr requested changes
Just some minor changes left, otherwise everything looks good.

2024-04-22 19:17 UTC, chrisduerr commented on themes/enfocado_dark.toml
> +# Theme: enfocado_nature_dark
There's still a reference to the old theme name here.

2024-04-22 19:17 UTC, chrisduerr commented on themes/enfocado_light.toml
> +# Theme: enfocado_nature_light
There's still a reference to the old theme name here.

2024-04-23 23:53 UTC, codex0x09 commented on themes/enfocado_light.toml
> +# Theme: enfocado_nature_light
Oops, I'm sorry about that

2024-04-24 00:03 UTC, codex0x09 commented
Mr @chrisduerr 
Thank you from bottom of my heart, I learn a lot from you (>^.^<).

2024-04-24 03:18 UTC, chrisduerr approved these changes

2024-04-24 03:18 UTC, merged